package com.nigelwilliams.app.models.enums;

public enum FoodPrepActivityType {
    NONE,
    MAKE_SALAD,
    MAKE_CEREAL,
    MAKE_EASY_SANDWICH,
    MAKE_MEDIUM_SANDWICH,
    MAKE_DIFFICULT_SANDWICH,
    COOK_EASY_BREAKFAST,
    COOK_MEDIUM_BREAKFAST,
    COOK_DIFFICULT_BREAKFAST,
    COOK_EASY_LUNCH,
    COOK_MEDIUM_LUNCH,
    COOK_DIFFICULT_LUNCH,
    COOK_EASY_DINNER,
    COOK_MEDIUM_DINNER,
    COOK_DIFFICULT_DINNER,
    COOK_EASY_DESSERT,
    COOK_MEDIUM_DESSERT,
    COOK_DIFFICULT_DESSERT,
}
